# Netlify configuration for Next.js 16
# Docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command
  command = "npm run build"

  # Directory with build output
  publish = ".next"

  # Node version
  [build.environment]
    NODE_VERSION = "20.11.0"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

    # Cache control
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets aggressively
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML pages
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects
[[redirects]]
  from = "/home"
  to = "/"
  status = 301
  force = true

# Environment-specific settings
[context.production]
  command = "npm run build"
  [context.production.environment]
    NODE_ENV = "production"
    NEXT_PUBLIC_APP_URL = "https://your-domain.netlify.app"

[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "production"

[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"

# Dev server settings
[dev]
  command = "npm run dev"
  port = 3002
  publish = ".next"
  autoLaunch = false
