"""initial_schema

Revision ID: 06014daac687
Revises: 
Create Date: 2025-10-25 16:35:40.882606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06014daac687'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs',
    sa.Column('agent_type', sa.Enum('SEO_WRITER', 'EMAIL_MARKETER', 'SOCIAL_MEDIA', 'ANALYST', 'OPTIMIZER', name='agenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_jobs_agent_type'), 'agent_jobs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_jobs_id'), 'agent_jobs', ['id'], unique=True)
    op.create_index(op.f('ix_agent_jobs_status'), 'agent_jobs', ['status'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('impressions', sa.Float(), nullable=True),
    sa.Column('clicks', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=True)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('budget_entries',
    sa.Column('resource_type', sa.Enum('OPENAI_API', 'WEB_SEARCH', 'FILE_SEARCH', 'IMAGE_GENERATION', 'EMBEDDING', name='resourcetype'), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('agent_job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_entries_agent_job_id'), 'budget_entries', ['agent_job_id'], unique=False)
    op.create_index(op.f('ix_budget_entries_id'), 'budget_entries', ['id'], unique=True)
    op.create_index(op.f('ix_budget_entries_resource_type'), 'budget_entries', ['resource_type'], unique=False)
    op.create_table('content_assets',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('BLOG', 'EMAIL', 'SOCIAL', 'VIDEO_SCRIPT', 'AD_COPY', 'LANDING_PAGE', name='contenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='contentstatus'), nullable=False),
    sa.Column('content_metadata', sa.JSON(), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('agent_job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_agent_job_id'), 'content_assets', ['agent_job_id'], unique=False)
    op.create_index(op.f('ix_content_assets_campaign_id'), 'content_assets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_assets_content_type'), 'content_assets', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_assets_id'), 'content_assets', ['id'], unique=True)
    op.create_index(op.f('ix_content_assets_status'), 'content_assets', ['status'], unique=False)
    op.create_index(op.f('ix_content_assets_title'), 'content_assets', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_assets_title'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_status'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_content_type'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_campaign_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_agent_job_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_budget_entries_resource_type'), table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_id'), table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_agent_job_id'), table_name='budget_entries')
    op.drop_table('budget_entries')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_agent_jobs_status'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_id'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_agent_type'), table_name='agent_jobs')
    op.drop_table('agent_jobs')
    # ### end Alembic commands ###
